apiVersion: apps/v1
kind: Deployment
metadata:
  name: bok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bok
  template:
    metadata:
      labels:
        app: bok
    spec:
      containers:
      - image: okteto.dev/bok:latest
        name: bok
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b1ff1f2b-521b-4a4f-8bb8-f3ba622f0e8c"
        - name: Vless_Path
          value: "/vl123"
        - name: Vmess_UUID
          value: "b1ff1f2b-521b-4a4f-8bb8-f3ba622f0e8c"
        - name: Vmess_Path
          value: "/vm345"
        - name: Share_Path
          value: "/v2link"
